### ISSUE TITLE
ToshihiroTamuraの成果物管理ディレクトリの作成

### ISSUE THREAD

**Issue by kazuki43zoo** [kazuki43zoo/spring-study-groups#3]
@ToshihiroTamura

ようこそ、Spring勉強会へ。第１号です！
実験的な勉強会なので、試行錯誤な感じになると思いますが、よろしく。

さっそくですが、ディレクトリとREADME.md作るだけの超簡単なIssueを対応お願いします。
あと、気兼ねなく質問してください。返事は夜になる可能性が高いけどね。

**Comment by btshimizukza** [comment]
@ToshihiroTamura 

masterにダイレクトコミットは原則NGです。

https://github.com/kazuki43zoo/spring-study-groups/tree/master#創作課題の管理について
に記載されているルールでお願いします。

https://github.com/kazuki43zoo/spring-study-groups/pull/2 を参考に。

よろしく。
